---
- hosts: localhost
  connection: local

  tasks:
  - name: "install base"
    become: yes
    package:
      name:
      - bash
      - curl
      - wget
      - neovim
      - ripgrep

  - name: "install go, python, terraform"
    become: yes
    package:
      name:
      - golang
      - python3
      - python3-pip
      # Skip terraform because we need to add the repo first
      # - terraform

  - name: "fnm check installed"
    register: fnm
    check_mode: no
    stat:
      path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.fnm/fnm"

  - name: "fnm download"
    when: not fnm.stat.exists
    get_url:
      url: https://fnm.vercel.app/install
      dest: /tmp/fnm-installer.sh

  - name: "fnm install"
    when: not fnm.stat.exists
    command:
      cmd: bash -s /tmp/fnm-installer.sh --skip-shell
      creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.fnm/fnm"

  - name: "fnm ensure .zshrc contains PATH"
    lineinfile:
      name: "{{ lookup('ansible.builtin.env', 'HOME') }}/.zshrc"
      line: 'export PATH="$HOME/.fnm:$PATH'
      state: present

  - name: "fnm ensure .zshrc contains eval"
    lineinfile:
      name: "{{ lookup('ansible.builtin.env', 'HOME') }}/.zshrc"
      line: 'eval $(fnm env --use-on-cd)'
      state: present

