---
- hosts: localhost
  connection: local

  tasks:
  - name: "install base"
    become: yes
    package:
      name:
      - bash
      - curl
      - unzip
      - wget
      - ripgrep
      - neovim

  - name: "install go"
    become: yes
    package:
      name: golang

  - name: "install python3"
    become: yes
    package:
      name:
      - python3
      - python3-pip

  - name: "install nodejs"
    become: yes
    package:
      name: nodejs

  # terraform
  - name: "terraform fedora dnf add hashicorp repo"
    become: yes
    yum_repository:
      name: hashicorp-stable
      description: Hashicorp Stable - $basearch
      baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
      gpgcheck: yes
      gpgkey: https://rpm.releases.hashicorp.com/gpg
    when: ansible_distribution == 'Fedora'

  - name: "terraform dnf install"
    become: yes
    dnf:
      update_cache: yes
      name: terraform

  # fnm
  - name: "fnm check installed"
    register: fnm
    check_mode: no
    stat:
      path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.fnm/fnm"

  - name: "fnm download"
    when: not fnm.stat.exists
    get_url:
      url: https://fnm.vercel.app/install
      dest: /tmp/fnm-installer.sh

  - name: "fnm install"
    command:
      cmd: bash /tmp/fnm-installer.sh --skip-shell
      creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.fnm/fnm"

  - name: "fnm ensure .zshrc contains PATH"
    lineinfile:
      name: "{{ lookup('ansible.builtin.env', 'HOME') }}/.zshrc"
      line: 'export PATH="$HOME/.fnm:$PATH'
      state: present

  - name: "fnm ensure .zshrc contains eval"
    lineinfile:
      name: "{{ lookup('ansible.builtin.env', 'HOME') }}/.zshrc"
      line: 'eval $(fnm env --use-on-cd)'
      state: present
